const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const kbJsonPath = path.join(projectRoot, 'src', 'kb.json');
const outputPath = path.join(projectRoot, 'src', 'KbData.js');

function main() {
  const kbRaw = fs.readFileSync(kbJsonPath, 'utf8');
  const kb = JSON.parse(kbRaw);
  const normalized = JSON.stringify(kb, null, 2);

  const output = `/**
 * Generated from src/kb.json by scripts/sync-kb.cjs.
 * Do not edit this file manually.
 */
var KB_JSON_SOURCE = ${JSON.stringify(normalized)};
`;

  fs.writeFileSync(outputPath, output, 'utf8');
  process.stdout.write(`Synced ${path.relative(projectRoot, outputPath)} from src/kb.json\n`);
}

main();
